### PR TITLE
fix: 修复明细表最左侧边框绘制问题

### LINKED ISSUE #1539: 🐛 明细表，开启序号时，左侧边框丢失
https://s2.antv.vision/zh/examples/basic/table#table
image

### PR DESCRIPTION
**Pull request by wjgogogo**
### 👀 PR includes

✨ Feature

- [ ] New feature

🎨 Enhance

- [ ] Code style optimization
- [ ] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [x] Solve the issue and close #1539 

🔧 Chore

- [ ] Test case
- [ ] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 📝 Description
明细表使用 grid 进行边框绘制时，对左侧边框是否绘制判断逻辑有问题，同时会导致行列冻结时，clip区域有错误，明细表绘制左边边框的场景有两种：
1. 存在行头冻结，需要为冻结的行头组添加边框
2. 不存在行头冻结，需要为默认的 Grid 组添加边框
### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
|       |       |

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

**Review by xingwanying — DISMISSED** [review]
要不要补个单测

**Review by lijinke666 — APPROVED** [review]

**Pull request merged**
