### PR TITLE
refactor: 简化 facet 构造参数

### PR DESCRIPTION
**Pull request by lijinke666**
### 👀 PR includes

🎨 Enhance

- [ ] Code style optimization
- [x] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

### 📝 Description

image

image

facet 的参数目前就是个大杂烩, 把所有东西全部拍平放在一起, 特别恶心, 完全没必要, 要取什么自己去 `s2.dataSet`, `s2.options` 取即可, 而不是疯狂套娃

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| ❌      | ✅     |

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

**Comment by lijinke666** [comment]
发现 明细表 滚动有 裁剪问题, 后面再来看
image

**Review by stone-lyl — APPROVED** [review]
LG

**Pull request merged**
