### PR TITLE
feat: 新增 "如何用 S2 买房" demo

### PR DESCRIPTION
**Pull request by stone-lyl**
### 👀 PR includes

✨ Feature

- [ ] New feature

🎨 Enhance

- [ ] Code style optimization
- [ ] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [ ] Solve the issue and close #0

🔧 Chore

- [ ] Test case
- [X] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 📝 Description
[feat: 新增 "如何用 S2 买房" demo](https://github.com/antvis/S2/commit/5f9a935a145475a92e15394cf6d0f32c832b474d)

### 🖼️ Screenshot

买房封面
     

### 🔍 Self Check before Merge

- [ ] Add or update relevant Docs.
- [ ] Add or update relevant Demos.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

**Comment by lijinke666** [comment]
S2 安装好了，请问房子去哪领

**Review by lcx-seima — APPROVED** [review]
LG

**Pull request merged**
