### PR TITLE
fix: 列头label存在数组，复制导出列头层级补齐错误

### PR DESCRIPTION
**Pull request by mmmml-zhao**
### 👀 PR includes

✨ Feature

- [ ] New feature

🎨 Enhance

- [ ] Code style optimization
- [ ] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [x] Solve the issue and close 

🔧 Chore

- [ ] Test case
- [ ] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 📝 Description

react demo 趋势分析表导出，表头与内容不对齐。
当headers存在数组，但不是每一列都存在数组时，仅需要对header[0]为数组的项进行补齐（当列各层级都是string类型时会补齐过多的空格）

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
|image   | image  |

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

**Comment by lijinke666** [comment]
感谢您的贡献, 还请在 packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/index-spec.tsx 补充一个相关单测

**Comment by mmmml-zhao** [comment]
> 感谢您的贡献, 还请在 packages/s2-react/**tests**/unit/components/sheets/strategy-sheet/index-spec.tsx 补充一个相关单测

已经添加

**Review by lijinke666 — APPROVED** [review]

**Pull request merged**
