### PR TITLE
feat: shift+按键支持横向滚动

### LINKED ISSUE #1940: 🙏 希望s2支持一下常规鼠标的交互
### 🖋 Description
如: shift+鼠标滚轮  为横向滚动 或者 鼠标放到横向滚动条上, 滑动滚轮也横向滚动

这个应该是默认支持的.  可以通过设置去不支持这项交互

### PR DESCRIPTION
**Pull request by serializedowen**
### 👀 PR includes

✨ Feature

- [ ] New feature

🎨 Enhance

- [ ] Code style optimization
- [ ] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [ ] Solve the issue and close #0

🔧 Chore

- [x] Test case
- [ ] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 📝 Description

shift+按键支持横向滚动

### 🖼️ Screenshot
Screen Recording 2022-11-29 at 14 58 28

### 🔍 Self-Check before the merge

- [x] Add or update relevant docs.
- [x] Add or update relevant demos.
- [x] Add or update test case.
- [x] Add or update relevant TypeScript definitions.

### CODE REVIEW

**Comment by lijinke666** [comment]
https://s2.antv.antgroup.com/manual/advanced/interaction/scroll
image

滚动这一章提一嘴 横向滚动 ?

**Comment by serializedowen** [comment]
> https://s2.antv.antgroup.com/manual/advanced/interaction/scroll image
> 
> 滚动这一章提一嘴 横向滚动 ?

image

看来feat应该改成fix了    D:

**Comment by haoqi0818** [comment]
> > https://s2.antv.antgroup.com/manual/advanced/interaction/scroll image
> > 滚动这一章提一嘴 横向滚动 ?
> 
> image
> 
> 看来feat应该改成fix了 D:

现在实测 Mac下可以 shift+滚轮 横向滚动，Win下不支持，不知道是不是兼容问题

**Comment by lijinke666** [comment]
> 看来feat应该改成fix了 D:

Mac 是自带横向滚动的, 这个主要是跨平台保证一致, feat 也没毛病

**Comment by serializedowen** [comment]
> 

mac下shift也是不行的 不知道的是不是改过了  动图description里面就有了  通过下吧

**Comment by lijinke666** [comment]
close #1958

**Review by lijinke666 — APPROVED** [review]

**Review by lijinke666 — APPROVED** [review]

**Pull request merged**
