### PR TITLE
feat: 支持resize最右侧column

### LINKED ISSUE #1592: 🙏明细表最后一列支持宽度拖拽
### 🧐 Suggest the API

|  name  |  type  | default  | description |
|----|----|----|----|
|  -  |  -  |  -  |  -  |

### PR DESCRIPTION
**Pull request by serializedowen**
### 👀 PR includes

✨ Feature

- [x] New feature

🐛 Bugfix

- [x] Solve the issue and close #1592 

🔧 Chore

- [x] Test case

### 📝 Description
原有逻辑对于最右侧column无法resize，因为事件挂载在canvas上，改为mousedown后监听window上的mousemove事件，并在mouseup时销毁

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| ❌      | ✅     |

Screen Recording 2022-07-25 at 8 50 07 PM

### 🔍 Self-Check before the merge

- [x] Add or update relevant docs.
- [x] Add or update relevant demos.
- [x] Add or update test case.
- [x] Add or update relevant TypeScript definitions.

### CODE REVIEW

**Comment by serializedowen** [comment]
遗留cursor图标待解，目前挂在resizeGroup上  设置cursor无效

**Review by YardWill — APPROVED** [review]
LG

**Pull request merged**
