### PR TITLE
feat: 支持自定义 G 5.0 插件和配置

### PR DESCRIPTION
**Pull request by lijinke666**
### 👀 PR includes

✨ Feature

- [x] New feature

### 📝 Description

1. 废弃 S2 这一层的 `supportCSSTransform` 和 `devicePixelRatio`, 这两个属性本质是透传到 `G`
2. 新增 `transformCanvasConfig` 支持自定义注册 `G` 插件和配置

```ts
import { Plugin as PluginRoughCanvasRenderer } from '@antv/g-plugin-rough-canvas-renderer';
import { Plugin as PluginA11y } from '@antv/g-plugin-a11y';

const s2Options = {
  transformCanvasConfig(renderer) {
    renderer.registerPlugin(new PluginRoughCanvasRenderer());
    renderer.registerPlugin(
      new PluginA11y({
        enableExtractingText: true,
      }),
    );

    console.log('当前已注册插件:', renderer.getPlugins(), renderer.getConfig());

    return {
      supportsCSSTransform: true,
      devicePixelRatio: 2,
      cursor: 'crosshair',
    };
  },
};
```
 
image

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| ❌      | ✅     |

### 🔍 Self-Check before the merge

- [x] Add or update relevant docs.
- [x] Add or update relevant demos.
- [x] Add or update test case.
- [x] Add or update relevant TypeScript definitions.

### CODE REVIEW

**Comment by lijinke666** [comment]
> **Size Change:** +53 kB (+16%) ⚠️
> 
> **Total Size:** 374 kB
> 
> Filename	Size	Change	
> `./packages/s2-core/dist/index.min.js`	280 kB	+53 kB (+23%)	🚨
> ℹ️ **View Unchanged**
> [compressed-size-action](https://github.com/preactjs/compressed-size-action)

体积有点不对劲

**Review by wjgogogo — APPROVED** [review]

**Comment by wjgogogo** [comment]
🐂🍺

**Pull request merged**
