### PR TITLE
fix(interaction): 修复隐藏列头配置更新时未覆盖上一次的配置 close #2495

### LINKED ISSUE #2495: 🐛明细表隐藏表头hiddenColumns更改，将部分字段取消隐藏，UI没有重新渲染
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   1.54.2   |
| @antv/s2-react |  1.46.0  |
### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

明细表初始指明hiddenColumnFields部分字段，重新更改hiddenColumnFields此时隐藏列并非新制定的hiddenColumnFields内列，而是取了两次hiddenColumnFields的交集

### ⌨️ Code Snapshots

```typescript
const App = () => {
  const [data, setData] = useState([]);
  const [hiddenColumnFields, setHiddenCols] = useState(["city", "price"]);
  useEffect(() => {
    fetch("https://assets.antv.antgroup.com/s2/basic-table-mode.json").then(
      (res) =>
        res.json().then((res) => {
          setData(res);
        })
    );
  }, []);

  const s2DataConfig = useMemo(() => {
    return {
      fields: {
        columns: ["province", "city", "type", "price", "cost"],
      },
      meta: [
        {
          field: "province",
          name: "省份",
        },
        {
          field: "city",
          name: "城市",
        },
        {
          field: "type",
          name: "商品类别",
        },
        {
          field: "price",
          name: "价格",
        },
        {
          field: "cost",
          name: "成本",
        },
      ],
      data: data,
    };
  }, [data]);

  const s2Options = useMemo(() => {
    return {
      width: 600,
      height: 480,
      interaction: {
        hiddenColumnFields: hiddenColumnFields,
      },
    };
  }, [hiddenColumnFields]);

  console.log(s2Options);

  return (
    <div>
      <button
        onClick={() => {
          setHiddenCols(["city"]);
        }}
      >
        change to sub
      </button>
      <button
        onClick={() => {
          setHiddenCols(["type"]);
        }}
      >
        change to other fields
      </button>
      <SheetComponent
        dataCfg={s2DataConfig}
        options={s2Options}
        sheetType="table"
      />
    </div>
  );
};
```

### 🔗 Reproduce Link

[复现链接](https://codesandbox.io/p/sandbox/serene-chaum-3dyg8f?file=%2Findex.tsx%3A53%2C36&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqxe9z6000063b6hcgvhv52v%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqxe9z6000023b6hzppw1lb5%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqxe9z6000033b6hbyvuuudo%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqxe9z6000053b6hvevso94a%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B51.48308583558236%252C48.51691416441764%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqxe9z6000023b6hzppw1lb5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqxe9z6000013b6ho6rkpxso%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A53%252C%2522startColumn%2522%253A36%252C%2522endLineNumber%2522%253A53%252C%2522endColumn%2522%253A36%257D%255D%257D%255D%252C%2522id%2522%253A%2522clqxe9z6000023b6hzppw1lb5%2522%252C%2522activeTabId%2522%253A%2522clqxe9z6000013b6ho6rkpxso%2522%257D%252C%2522clqxe9z6000053b6hvevso94a%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqxe9z6000043b6hoz80tx0n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqxe9z6000053b6hvevso94a%2522%252C%2522activeTabId%2522%253A%2522clqxe9z6000043b6hoz80tx0n%2522%257D%252C%2522clqxe9z6000033b6hbyvuuudo%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqxe9z6000033b6hbyvuuudo%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### 🤔 Steps to Reproduce

初始隐藏 `["city", "price"]`两个字段，点击 `change to sub` 按钮，此时UI没有变化
点击`change to other fields`改变hiddenColumnFields 为`['type']`,此时 `city`和`price`依然不可见

### 😊 Expected Behavior

预期根据最新指示的hiddenColumnFields控制隐藏列展示UI

### 😅 Current Behavior

取了几次指定options指定的hiddenColumnFields的交集

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |    macOS14.1.2     |
| Browser |    120.0.6099.129（正式版本） (arm64)     |

### LINKED ISSUE #2507: 🐛明细表隐藏列功能问题
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  1.53.0  |
| @antv/s2-react |  1.46.0  |
| @antv/s2-vue   |   -     |

### Sheet Type

TableSheet（明细表）

### 🖋 Description

隐藏列功能有问题，具体见录屏

https://github.com/antvis/S2/assets/34603922/9b07b353-9513-4c8a-8de9-e147793ed3ec

### ⌨️ Code Snapshots
官网示例就可以复现 

### 🔗 Reproduce Link

https://s2.antv.vision/zh/examples/react-component/switcher/#table

| Environment | Info |
| ------- | ------- |
| System  |   mac      |
| Browser |    chrome： 120.0.6099.129     |

### PR DESCRIPTION
**Pull request by lijinke666**
### 👀 PR includes

🐛 Bugfix

- [x] Solve the issue and close #2495 

### 📝 Description

通过 `interaction.hiddenColumnFields` 配置动态改变隐藏列的场景中, 由于最终都是通过 `s2.setOptions({ ... })` 的方式, 导致配置项会 `merge`, 而不是覆盖, 对于这种场景应该清除上一次记录的隐藏列信息.

https://github.com/antvis/S2/blob/96ffa9f1817de6c9197b49d4b5fd4d9a65e70973/packages/s2-react/src/hooks/useSpreadSheet.ts#L104-L111

```tsx
 const [hiddenColumnFields, setHiddenCols] = useState(["city", "price"]);

 const s2Options =  {
    width: 600,
    height: 480,
    interaction: {
      hiddenColumnFields: hiddenColumnFields,
    },
  };

  <button
    onClick={() => {
      setHiddenCols(['city']);
    }}
  >
    change city
  </button>
  <button
    onClick={() => {
      setHiddenCols(['type']);
    }}
  >
    change type
  </button>
  <button
    onClick={() => {
      setHiddenCols([]);
    }}
  >
    reset
  </button>

  <SheetComponent
    dataCfg={s2DataConfig}
    options={s2Options}
    sheetType="table"
  />
```

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| Kapture 2024-01-22 at 11 34 00 | Kapture 2024-01-22 at 11 31 44 |
| Kapture 2024-01-22 at 15 50 16 | Kapture 2024-01-22 at 15 48 40 |

### 🔗 Related issue link

closes #2507 #2495 

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

**Comment by lijinke666** [comment]
ref #2511

**Review by wjgogogo — APPROVED** [review]

**Pull request merged**
