### PR TITLE
feat: 支持自定义设备像素比

### LINKED ISSUE #1050: 🐛 SheetComponent 在options.hdAdapter为true的情况下渲染模糊
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | -   1.7.0      |
| @antv/s2-react | -  1.7.0       |

### 🖋 Description
SheetComponent 在options.hdAdapter为true的情况下渲染模糊，设备DPR为1（已在钉群反馈过）

### PR DESCRIPTION
**Pull request by lijinke666**
### 👀 PR includes

✨ Feature

- [x] New feature

🐛 Bugfix

- [x] Solve the issue

### 📝 Description

1. 支持自定义 devicePixelRatio, 兼容高清场景
2. 修复缩放表格为原始大小后, canvas 宽高没有还原的问题

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| ❌      | ✅     |

### 🔗 Related issue link

close #1050 

### 🔍 Self Check before Merge

- [ ] Add or update relevant Docs.
- [ ] Add or update relevant Demos.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

**Review by xingwanying — APPROVED** [review]
LG

**Review by wjgogogo — APPROVED** [review]

**Pull request merged**
