### PR TITLE
feat: ✨ init strategy sheet

### PR DESCRIPTION
**Pull request by xingwanying**
### 👀 PR includes

✨ Feature

- [x] init strategy sheet.
- [x]  add cornerText for the options.

### 🖼️ Screenshot

image

### 🔍 Self Check before Merge

- [x] Add or update relevant Docs.
- [x] Add or update relevant Demos.
- [x] Add or update relevant TypeScript definitions.

### CODE REVIEW

**Review by lijinke666 — APPROVED** [review]

**Comment by xingwanying** [comment]
TODO: 单元格 objectText方法优化

**Pull request merged**
