### PR TITLE
feat(interaction): 行头支持滚动刷选

### LINKED ISSUE #2075: 🙏 透视表行头支持滚动刷选
### 🖋 Description

同 dataCell 交互

image

### 🧐 Suggest the API

| name | type | default | description |
| ---- | ---- | ------- | ----------- |
| -    | -    | -       | -           |

### PR DESCRIPTION
**Pull request by lijinke666**
### 👀 PR includes

✨ Feature

- [x] New feature

🎨 Enhance

- [ ] Code style optimization
- [ ] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [ ] Solve the issue and close #0

🔧 Chore

- [ ] Test case
- [ ] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 📝 Description

- 行头增加刷选时自动滚动, 支持 **水平滚动** 和 **垂直滚动**, 可以用于统计单元格个数, 复制
- 增加行头区域的滚动方法, 原本 `updateScrollOffset` 只支持数值区域的滚动 (即 `offsetX` 和 `offsetY`), 现在行头滚动需要增强其能力, `rowHeaderOffsetX`

```ts
s2.updateScrollOffset({
  rowHeaderOffsetX: {
    value: 50,
    animate: true,
  },
});
```

TODO:

- [x] 兼容复制
- [x] 单测
- [x] 文档

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| Kapture 2023-02-21 at 17 14 42 | Kapture 2023-02-21 at 17 12 17 |

### 🔗 Related issue link

close #2075 

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

**Review by stone-lyl — COMMENTED** [review]
列头为什么刷选

**Review by stone-lyl — COMMENTED** [review]
刷选的蒙层超出了行头

**Comment by lijinke666** [comment]
刷选的蒙层超出了行头 和 列头刷选 下个版本加

**Review by GaoFuhong — DISMISSED** [review]

**Review by GaoFuhong — APPROVED** [review]

**Review by GaoFuhong — APPROVED** [review]

**Review by GaoFuhong — APPROVED** [review]

**Pull request merged**
