### PR TITLE
fix: 明细表奇数行背景色不生效修复

### LINKED ISSUE #1748: 🐛斑马纹 奇数行背景色 crossBackgroundColor 透视表正常明细表失效
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |      ^1.25.0    |
| @antv/s2-react |     ^1.23.0     |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 🖋 Description
明细表奇数行背景色 crossBackgroundColor 不生效

### PR DESCRIPTION
**Pull request by serializedowen**
### 👀 PR includes

✨ Feature

- [ ] New feature

🎨 Enhance

- [ ] Code style optimization
- [ ] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [x] Solve the issue and close #1748 

🔧 Chore

- [ ] Test case
- [ ] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 🖼️ Screenshot
image

| Before | After |
| ------ | ----- |
| ❌      | ✅     |

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

**Review by YardWill — APPROVED** [review]
牛的

**Comment by lijinke666** [comment]
加个单测吧

**Pull request merged**
