### PR TITLE
docs: 增加成都疫情数据场景案例

### PR DESCRIPTION
**Pull request by wjgogogo**
### 👀 PR includes

✨ Feature

- [ ] New feature

🎨 Enhance

- [ ] Code style optimization
- [ ] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [ ] Solve the issue and close #0

🔧 Chore

- [ ] Test case
- [x] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 🖼️ Screenshot
新增场景案例, 为本月宣发文章做准备

| Before | After |
| ------ | ----- |
| ❌      | ✅     |

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

**Review by xingwanying — COMMENTED** [review]
数据还是走cdn，申请好了跟你说

**Comment by wjgogogo** [comment]
> 数据还是走cdn，申请好了跟你说

@xingwanying ok了

**Comment by wjgogogo** [comment]
> image 箭头和数值颜色是不是不对

这个是改了的，只是截图没有换，我换一张截图

**Review by xingwanying — APPROVED** [review]
LG

**Review by stone-lyl — APPROVED** [review]

**Pull request merged**
