### PR TITLE
fix: 修复中英文标点符号

### LINKED ISSUE #2440: 🐛  `tooltip`  中 `summary` 组件 的 `总和` 前后括号不一致, 期望跟vue组件一致，不渲染前后括号
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |    1.44.2     |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

image
现状：左括号用的是双字节（中文括号），右括号用的是单字节(英文括号)

期望：跟vue 组件保持一致， “总和”左右两边的括号应该不渲染。

### ⌨️ Code Snapshots

源代码地址：  https://github.com/antvis/S2/blob/master/packages/s2-react/src/components/tooltip/components/summary.tsx
   ```ts
return (
          <div
            key={`${name}-${value}`}
            className={`${TOOLTIP_PREFIX_CLS}-summary-item`}
          >
            {name ? (
              <span className={`${TOOLTIP_PREFIX_CLS}-summary-key`}>
                {name} （{i18n('总和')})
              </span>
            ) : (
          </div>
       );
```
vue版本：
   ```ts
      <span :class="`${TOOLTIP_PREFIX_CLS}-summary-key`">
        {{ summary.name }} {{ i18n('总和') }}
      </span>
   ```

### 🔗 Reproduce Link
https://s2.antv.antgroup.com/zh/examples/react-component/sheet/#pivot （官方demo, 不需要任何改动）

### 🤔 Steps to Reproduce
 点击 `数量` 等任意分类，出现弹窗，找到总和，观察前后括号

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |    all     |
| Browser |    all     |

### PR DESCRIPTION
**Pull request by wjgogogo**
### 👀 PR includes

✨ Feature

- [ ] New feature

🎨 Enhance

- [ ] Code style optimization
- [ ] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [x] Solve the issue and close #2440 

🔧 Chore

- [ ] Test case
- [ ] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| ❌      | ✅     |

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

**Comment by xulingling0** [comment]
希望跟 vue 组件保持一致，把前后括号去掉，我已经改好了
https://github.com/antvis/S2/pull/2443

**Comment by lijinke666** [comment]
建议这样改 

https://github.com/antvis/S2/pull/2443#issuecomment-1835701058

**Comment by xulingling0** [comment]
啥时候发版呀

**Review by lijinke666 — APPROVED** [review]

**Pull request merged**
