### PR TITLE
docs: 新增马赛克图

### PR DESCRIPTION
**Pull request by xingwanying**
### 👀 PR includes

🔧 Chore

- [ ] Test case
- [x] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 📝 Description

Data supported by ❤️ @pearmini

### CODE REVIEW

**Comment by wjgogogo** [comment]
tql👍👍👍

**Comment by stone-lyl** [comment]
tql👍👍👍

**Comment by lijinke666** [comment]
tql👍👍👍

**Review by lijinke666 — APPROVED** [review]

**Pull request merged**
