### PR TITLE
fix(export): 优化复制数据到剪贴板的逻辑

### PR DESCRIPTION
**Pull request by lijinke666**
### 👀 PR includes

✨ Feature

- [ ] New feature

🎨 Enhance

- [x] Code style optimization
- [x] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [ ] Solve the issue and close #0

🔧 Chore

- [ ] Test case
- [x] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 📝 Description

1. 优化复制数据的处理逻辑
2. 优化相关文档
3. 修复类型错误

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| ❌      | ✅     |

### 🔗 Related issue link

cc @YardWill @zxc0328 

### 🔍 Self Check before Merge

- [x] Add or update relevant Docs.
- [x] Add or update relevant Demos.
- [x] Add or update relevant TypeScript definitions.

### CODE REVIEW

**Review by xingwanying — DISMISSED** [review]
LG

**Review by YardWill — DISMISSED** [review]

**Review by stone-lyl — APPROVED** [review]
666

**Review by stone-lyl — APPROVED** [review]

**Pull request merged**
